use crate::db_services::db_objects::{PersistenceStatus, PrimaryKey};

use sha3::{Digest, Sha3_256};
use sqlx::pool::Pool;
use sqlx::postgres::Postgres;
use sqlx::FromRow;
use std::fmt;

/// SQL: Prepared statement used when inserting a record into the table mandants.
const MANDANT_INSERT: &str = "INSERT INTO mandants (association_name, website, email) 
VALUES ($1, $2, $3) returning id::text";

/// SQL: Prepared statement selecting one record from mandants by its UUID which is its primary key.
const MANDANT_SELECT_BY_UUID: &str = "SELECT association_name, website, email from mandants 
    where id = $1::uuid";

/// SQL: Prepared statment updating one records from mandants.
const MANDANT_UPDATE_BY_UUID: &str =
    "UPDATE mandants set association_name = $1, website = $2, email = $3 
    where id = $4::uuid  returning id::text";

#[derive(Debug, FromRow)]
/// Represents one records of the table "mandants".
pub struct Mandant {
    /// Primary key - UUID generated by the database.
    id: String,
    /// Name or the organisation or association.
    pub association_name: String,
    /// Website of the organisation-
    pub website: String,
    /// Official email address of the organisation
    pub email: String,
    /// SHA3 value calculated over the values
    /// - association_name
    /// - website
    /// - email
    ///
    /// This value is primarily used when calling the method
    /// - persist
    ///
    /// The values mentioned are calculted again and if the SHA3 value is different, an update is performed and the new SHA3 value assigned to hash_value.
    hash_value: String,
    persistence_status: PersistenceStatus,
}

#[derive(Debug, FromRow)]
/// Mapping struct used for a select by UUID (id)
struct SelectById {
    pub association_name: String,
    pub website: String,
    pub email: String,
}

/// Generating a SHA3 token over a vector of string references.
fn gen_sha3(tokens: Vec<&str>) -> String {
    let mut hasher = Sha3_256::new();
    hasher.update(tokens.join("___"));
    hex::encode(hasher.finalize())
}

impl Mandant {
    /// Constructor mandant
    pub fn new(association_name: String, website: String, email: String) -> Self {
        let hash_value = gen_sha3(vec![&association_name, &website, &email]);
        Mandant {
            id: String::from(""),
            association_name,
            website,
            email,
            hash_value,
            persistence_status: PersistenceStatus::New,
        }
    }

    /// Mapping a query result and returing a instance of Mandant.
    fn map_query_result(
        id: String,
        association_name: String,
        website: String,
        email: String,
        persistence_status: PersistenceStatus,
    ) -> Self {
        let hash_value = gen_sha3(vec![&association_name, &website, &email]);
        Mandant {
            id,
            association_name,
            website,
            email,
            hash_value,
            persistence_status,
        }
    }

    /// Returing a reference of the primary key.
    pub fn primary_key(&self) -> &str {
        &self.id
    }

    /// Returning a reference of the persistence status.
    pub fn persistence_status(&self) -> &PersistenceStatus {
        &self.persistence_status
    }

    /// Persisting the tupel to the database. It will either perform
    /// an insert or an update.
    /// An insert is performed if the id (primary key) is empty and an update is performed
    /// if the SHA3 value newly calculated is different.
    pub async fn persist(&mut self, pool: &Pool<Postgres>) {
        if self.id.is_empty() {
            self.insert(pool).await;
        } else {
            let hash_value = gen_sha3(vec![&self.association_name, &self.website, &self.email]);
            if self.hash_value != hash_value {
                self.update(pool).await;
                if self.persistence_status() == &PersistenceStatus::Success {
                    self.hash_value = hash_value;
                }
            } else {
                self.persistence_status = PersistenceStatus::Clean;
            }
        }
    }

    async fn insert(&mut self, pool: &Pool<Postgres>) -> bool {
        let insert_result = sqlx::query_as::<_, PrimaryKey>(MANDANT_INSERT)
            .bind(&self.association_name)
            .bind(&self.website)
            .bind(&self.email)
            .fetch_one(pool)
            .await;
        //sqlx::query_as::<DB, O>(INSERT_MANDANT);
        let mut success = true;
        match insert_result {
            Ok(p) => {
                self.id = p.id;
            }
            Err(_e) => success = false,
        }
        success
    }

    pub async fn select(uuid: String, pool: &Pool<Postgres>) -> Self {
        let select_result = sqlx::query_as::<_, SelectById>(MANDANT_SELECT_BY_UUID)
            .bind(&uuid)
            .fetch_one(pool)
            .await;
        match select_result {
            Ok(s) => Mandant::map_query_result(
                uuid,
                s.association_name,
                s.website,
                s.email,
                PersistenceStatus::Success,
            ),
            Err(e) => Mandant::map_query_result(
                uuid,
                String::from(""),
                String::from(""),
                String::from(""),
                PersistenceStatus::Error(format!("{}", e)),
            ),
        }
    }

    async fn update(&mut self, pool: &Pool<Postgres>) {
        let update_result = sqlx::query_as::<_, PrimaryKey>(MANDANT_UPDATE_BY_UUID)
            .bind(&self.association_name)
            .bind(&self.website)
            .bind(&self.email)
            .bind(&self.id)
            .fetch_one(pool)
            .await;
        match update_result {
            Ok(_s) => self.persistence_status = PersistenceStatus::Success,
            Err(e) => self.persistence_status = PersistenceStatus::Error(format!("{}", e)),
        }
    }
}

impl fmt::Display for Mandant {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "id: {}, association_name: {}, website: {}, email: {}",
            self.id, self.association_name, self.website, self.email
        )
    }
}
